### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by lparolari**
For those who do not have the sbt installed and want to play the game docker may be the solution!

Added:
- docker support with docker composer
- docs in readme

### CODE REVIEW

**Comment by TheElectronWill** [comment]
Thanks for the contribution!

Note that you can use the [sbt](../blob/master/sbt) script in the repo without installing anything :)
But it could still be handy to have a good dockerfile.

**Comment by lparolari** [comment]
Oh sorry, didn't see it. Thank you for the clarification.

**Comment by TheElectronWill** [comment]
no problem

**Comment by lparolari** [comment]
Sorry for bothering.

Can you please add the label "hacktoberfest-accepted" to the PR? Otherwise my PR does not get counted :(

Hacktoberfest disclaimer:

```
Ineligible Repository

Your PR was submitted to a repository that is not participating in
Hacktoberfest.  Maintainers of the repository can add the
"hacktoberfest" topic to their repository if they wish to
participate. Alternatively, an individual PR can be opted-in with a
maintainer adding the "hacktoberfest-accepted" label to the PR.
```

Thank you!

**Comment by TheElectronWill** [comment]
Yeah I saw that DigitalOcean finally did something to prevent spam. Label added :)

**Pull request merged**
